mutation registration($username: String!, $password: String!, $fullName: String!) {
    registration(full_name: $fullName, username: $username, password: $password){
        id
        fullName
        username
        roles {
            id
            name
            allowedOperations
        }
        creditSet {
            id
            borrower {
                id
                fullName
            }
            creditSize
            monthsCount
            startDate
            percent
            name
        }
    }
}