version: "3"
networks:
  payments-app:

services:
  server:
    build: .
    ports:
      - "8080:8080"
    networks:
      - payments-app
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/02_data.sql
    networks:
      - payments-app

